//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("Wyam")]
[assembly: AssemblyVersion("2.2.14")]
[assembly: AssemblyFileVersion("2.2.14")]
[assembly: AssemblyInformationalVersion("2.2.14")]
[assembly: AssemblyCopyright("Copyright © Wyam Contributors")]